const gentils = [
  "salut", "bonjour", "merci", "comment ça va", "bravo", "félicitations", "super", "cool", "génial", "bien joué",
  "chouette", "youpi", "top", "waouh", "courage", "trop bien", "formidable", "sympa", "adorable", "bienvenue",
  "s'il te plaît", "à bientôt", "bon courage", "trop chou", "gentil", "joli", "magnifique", "excellent", "trop mignon", "beau travail",
  "tu es super", "tu es génial", "je t'aime bien", "bonne chance", "t'es trop cool", "tu assures", "merci beaucoup", "grand merci", "merci infiniment", "you are amazing",
  "tu es gentil", "adorable ami", "copain sympa", "belle journée", "j'aime ton sourire", "tu es brillant", "bonne humeur", "plein de joie", "tu m'inspires", "merci à toi",
  "très chouette", "meilleur ami", "adorable sourire", "beau travail", "tu es formidable", "souriant", "positif", "rayonnant", "lumineux", "tu es talentueux",
  "généreux", "tu es parfait", "trop sympa", "j’adore", "tu brilles", "tes idées sont super", "tu es unique", "j’ai confiance en toi", "tu es spécial", "brillant esprit",
  "belle âme", "cœur en or", "si attentionné", "gentillesse infinie", "ton rire est magique", "tu m’apportes du bonheur", "tu es une belle personne", "super ami", "meilleur soutien", "merci pour tout",
  "esprit ouvert", "intelligent", "très attentionné", "super génie", "merveilleux", "très gentil", "plein de bonté", "trop gentil", "tu es généreux", "rien que du bonheur",
  "merci mon ami", "je suis reconnaissant", "très doux", "humain exceptionnel", "rempli d’amour", "beau cœur", "très attachant", "toujours positif", "me fait sourire", "chaleureux",
  // ... (9500 autres mots gentils à ajouter)
];

const questions = {
  "quelle est la capitale de la france": "La capitale de la France est Paris.",
  "combien de planètes dans le système solaire": "Il y a 8 planètes dans le système solaire.",
  "quelle est la distance entre la terre et la lune": "Environ 384 400 kilomètres.",
  "qui a inventé l'ampoule": "Thomas Edison est souvent crédité, mais plusieurs inventeurs ont contribué.",
  "quelle est la langue la plus parlée au monde": "Le mandarin (chinois) est la langue la plus parlée.",
  "qu'est-ce que l'eau": "L'eau est une substance composée de deux atomes d'hydrogène et d'un atome d'oxygène (H2O).",
  "quelle est la plus grande montagne": "L’Everest est la plus haute montagne du monde.",
  "comment s'appelle notre galaxie": "Notre galaxie s'appelle la Voie Lactée.",
  "quel est le plus grand animal du monde": "La baleine bleue est le plus grand animal connu.",
  "qui a écrit harry potter": "J.K. Rowling est l’auteure de Harry Potter.",
  "combien de continents y a-t-il sur Terre": "Il y a 7 continents sur Terre.",
  "quelle est la capitale de l'italie": "La capitale de l'Italie est Rome.",
  "quelle est la température de congélation de l'eau": "0 degré Celsius.",
  "quel est l'animal le plus rapide": "Le guépard est l'animal terrestre le plus rapide.",
  "qui a peint la joconde": "La Joconde a été peinte par Léonard de Vinci.",
  "quelle est la planète la plus proche du soleil": "La planète la plus proche du Soleil est Mercure.",
  "quand a eu lieu la révolution française": "En 1789.",
  "combien de jours y a-t-il dans une année": "Il y a 365 jours dans une année (366 lors des années bissextiles).",
  "qui a créé facebook": "Facebook a été créé par Mark Zuckerberg.",
  "quelle est la capitale du japon": "La capitale du Japon est Tokyo.",
  "qui a découvert l'amérique": "Christophe Colomb en 1492.",
  "quel est l'élément chimique H": "H est l'hydrogène.",
  "qu'est-ce qu'un volcan": "Un volcan est une ouverture dans la croûte terrestre qui permet la sortie de magma.",
  "quelle est la capitale de l'espagne": "Madrid.",
  "combien de pattes a une araignée": "8 pattes.",
  "qui est le président de la france": "Emmanuel Macron (en 2025).",
  "qu'est-ce que la gravité": "C'est la force qui attire les objets vers le centre de la Terre.",
  "quel est l'océan le plus grand": "L'océan Pacifique.",
  "combien de zéros dans un milliard": "Il y a 9 zéros dans un milliard.",
  "qu'est-ce qu'une étoile": "Une étoile est une boule de gaz très chaude qui émet de la lumière.",
  "quelle est la capitale de l’allemagne": "La capitale de l’Allemagne est Berlin.",
  "qu'est-ce qu'une cellule": "La cellule est l'unité de base de tous les êtres vivants.",
  "quelle est la vitesse de la lumière": "Environ 299 792 kilomètres par seconde.",
  "quand est née la tour eiffel": "La Tour Eiffel a été inaugurée en 1889.",
  "que veut dire adn": "ADN signifie Acide DésoxyriboNucléique.",
  "quelle est la capitale du canada": "La capitale du Canada est Ottawa.",
  "qu’est-ce que la photosynthèse": "C'est le processus par lequel les plantes transforment la lumière du soleil en énergie.",
  "quel est le plus grand désert": "Le désert de l'Antarctique est le plus grand désert.",
  "qu’est-ce qu’un arc-en-ciel": "Un arc-en-ciel est un phénomène optique causé par la réfraction et la réflexion de la lumière dans les gouttes d'eau.",
  "combien de dents a un humain adulte": "32 dents.",
  "que se passe-t-il si la Terre arrêtait de tourner": "Les effets seraient catastrophiques : vents violents, tremblements de terre, etc.",
  "pourquoi le ciel est bleu": "C'est à cause de la diffusion de la lumière du soleil dans l'atmosphère.",
  "qu'est-ce que l'effet de serre": "C'est un phénomène naturel qui retient la chaleur dans l'atmosphère terrestre.",
  "comment fabrique-t-on du papier": "À partir de fibres de bois, qui sont broyées, blanchies puis séchées.",
  "quels sont les cinq sens": "La vue, l'ouïe, le toucher, le goût et l'odorat."
};
